#!/usr/bin/env sh
# generate-mobile-config.sh
# Read the server lists tracked in this repo (authbot / authws) and produce
# import-ready config for mobile SSH/SSL-tunnel apps (HTTP Injector, HTTP Custom,
# SocksHTTP, NapsternetV, etc.). Runs from a USB stick, a PC, or Termux on Android.
#
# The repo only stores each server's display name, host, and status. Ports,
# username/password, and the SNI/payload are per-account and are filled from
# environment variables (or left as clearly-marked placeholders) so nothing
# secret is committed.
#
# Usage:
#   sh generate-mobile-config.sh [output_dir]
#
# Optional environment variables (override the defaults shown):
#   VPN_USER=your_ssh_user
#   VPN_PASS=your_ssh_password
#   VPN_SNI=bug.host.com          # SNI / TLS host used for SSL tunnels
#   VPN_WS_PORT=80                # WebSocket (ws) port
#   VPN_SSL_PORT=443             # SSL/TLS (wss) port
#   VPN_PAYLOAD='GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf]'

set -eu

# --- locate the repo root (script lives in <repo>/vpn-mobile) -----------------
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
REPO_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

AUTHBOT="$REPO_DIR/authbot"
AUTHWS="$REPO_DIR/authws"

OUT_DIR="${1:-$SCRIPT_DIR/dist}"
mkdir -p "$OUT_DIR"

# --- defaults (placeholders make it obvious what still needs editing) ---------
VPN_USER="${VPN_USER:-YOUR_USERNAME}"
VPN_PASS="${VPN_PASS:-YOUR_PASSWORD}"
VPN_SNI="${VPN_SNI:-YOUR_SNI_OR_BUGHOST}"
VPN_WS_PORT="${VPN_WS_PORT:-80}"
VPN_SSL_PORT="${VPN_SSL_PORT:-443}"
VPN_PAYLOAD="${VPN_PAYLOAD:-GET / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf]}"

SERVERS_TXT="$OUT_DIR/mobile-vpn-servers.txt"
HTTP_INJECTOR="$OUT_DIR/http-injector-import.txt"
JSON_OUT="$OUT_DIR/mobile-vpn-servers.json"

# --- helpers ------------------------------------------------------------------
is_active() {
  # $1 = status token; treat "true" (any case) as active
  case "$1" in
    [Tt][Rr][Uu][Ee]) return 0 ;;
    *) return 1 ;;
  esac
}

emit_header_txt() {
  {
    echo "# Mobile VPN server list"
    echo "# Generated by vpn-mobile/generate-mobile-config.sh"
    echo "# Source: authbot (SSH) + authws (WebSocket/SSL) in this repo"
    echo "#"
    echo "# WS port : $VPN_WS_PORT      SSL port: $VPN_SSL_PORT"
    echo "# User    : $VPN_USER"
    echo "# SNI/bug : $VPN_SNI"
    echo "#"
    echo "# Name | Host | WS(ws://host:$VPN_WS_PORT) | SSL(wss://host:$VPN_SSL_PORT) | Status"
    echo "# --------------------------------------------------------------------"
  } > "$SERVERS_TXT"
}

emit_header_injector() {
  {
    echo "# HTTP Injector / HTTP Custom style config"
    echo "# Import per server, or copy a block into a new profile."
    echo "# Replace $VPN_USER / $VPN_PASS / $VPN_SNI before use."
    echo ""
  } > "$HTTP_INJECTOR"
}

# --- parse authbot (SSH servers): lines look like "### Name IP true" ----------
count=0
active=0
emit_header_txt
emit_header_injector

# Build JSON incrementally
printf '{\n  "generated_by": "vpn-mobile/generate-mobile-config.sh",\n  "ws_port": %s,\n  "ssl_port": %s,\n  "servers": [\n' \
  "$VPN_WS_PORT" "$VPN_SSL_PORT" > "$JSON_OUT"
first_json=1

parse_line() {
  # $1 = full line, $2 = comment marker to strip (### or #&)
  line=$1
  marker=$2
  # strip the marker prefix and surrounding whitespace
  rest=$(printf '%s' "$line" | sed "s/^$marker[[:space:]]*//")
  [ -n "$rest" ] || return 0

  name=$(printf '%s' "$rest" | awk '{print $1}')
  host=$(printf '%s' "$rest" | awk '{print $2}')
  status=$(printf '%s' "$rest" | awk '{print $3}')
  [ -n "$name" ] && [ -n "$host" ] || return 0

  count=$((count + 1))

  # status column for the txt list
  if [ -n "${status:-}" ] && is_active "$status"; then
    st="active"
    active=$((active + 1))
  else
    st="${status:-unknown}"
  fi

  printf '%-16s | %-18s | ws://%s:%s | wss://%s:%s | %s\n' \
    "$name" "$host" "$host" "$VPN_WS_PORT" "$host" "$VPN_SSL_PORT" "$st" >> "$SERVERS_TXT"

  # per-server importable block
  {
    echo "[$name]"
    echo "remote_host   = $host"
    echo "ssh_user      = $VPN_USER"
    echo "ssh_pass      = $VPN_PASS"
    echo "ws_port       = $VPN_WS_PORT"
    echo "ssl_port      = $VPN_SSL_PORT"
    echo "sni           = $VPN_SNI"
    payload=$(printf '%s' "$VPN_PAYLOAD" | sed "s/\[host\]/$host/g")
    echo "payload       = $payload"
    echo ""
  } >> "$HTTP_INJECTOR"

  # JSON entry
  if [ "$first_json" -eq 1 ]; then first_json=0; else printf ',\n' >> "$JSON_OUT"; fi
  printf '    {"name": "%s", "host": "%s", "status": "%s"}' "$name" "$host" "$st" >> "$JSON_OUT"
}

if [ -f "$AUTHBOT" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      '### '*) parse_line "$line" '###' ;;
    esac
  done < "$AUTHBOT"
else
  echo "warning: $AUTHBOT not found, skipping SSH server list" >&2
fi

# --- parse authws (WebSocket/SSL): lines look like "#& Name ... value" --------
if [ -f "$AUTHWS" ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      '#& '*)
        # only rows whose 2nd field is an IP-looking host are usable as servers
        host=$(printf '%s' "$line" | sed 's/^#&[[:space:]]*//' | awk '{print $NF}')
        case "$host" in
          [0-9]*.[0-9]*.[0-9]*.[0-9]*)
            name=$(printf '%s' "$line" | sed 's/^#&[[:space:]]*//' | awk '{print $1}')
            parse_line "#& $name $host true" '#&'
            ;;
        esac
        ;;
    esac
  done < "$AUTHWS"
fi

printf '\n  ],\n  "total": %s,\n  "active": %s\n}\n' "$count" "$active" >> "$JSON_OUT"

echo "Done."
echo "  Servers parsed : $count ($active active)"
echo "  Output dir     : $OUT_DIR"
echo "    - $(basename "$SERVERS_TXT")"
echo "    - $(basename "$HTTP_INJECTOR")"
echo "    - $(basename "$JSON_OUT")"
echo ""
echo "Next: set VPN_USER / VPN_PASS / VPN_SNI (and ports) and re-run to bake"
echo "real credentials in, then import the file into your mobile tunnel app."
